import { defineItem } from "@ballmac-ui/metadata"

export default defineItem({
  name: "template-auth-kit",
  type: "registry:block",
  title: "Auth Kit: complete sign-in flow",
  description:
    "Seven auth pages in three switchable layouts (centered, split with art, frosted glass): sign in, sign up with a live password checklist, six-digit verification, forgot and reset password, team invite and a three-step onboarding.",
  category: "templates",
  templateKind: "application",
  templatePages: [
    { title: "Playground", example: "template-auth-kit-demo" },
    { title: "Sign in", example: "template-auth-kit-sign-in", path: "/auth/sign-in" },
    { title: "Sign up", example: "template-auth-kit-sign-up", path: "/auth/sign-up" },
    { title: "Verify", example: "template-auth-kit-verify", path: "/auth/verify" },
    { title: "Forgot", example: "template-auth-kit-forgot", path: "/auth/forgot" },
    { title: "Reset", example: "template-auth-kit-reset", path: "/auth/reset" },
    { title: "Invite", example: "template-auth-kit-invite", path: "/auth/invite" },
    { title: "Onboarding", example: "template-auth-kit-onboarding", path: "/auth/onboarding" },
  ],
  fonts: ["Outfit"],
  featured: true,
  tags: ["template", "auth", "login", "signup", "verification", "onboarding", "password", "otp"],
  files: [
    { path: "components/templates/auth-kit/auth-kit-fonts.ts" },
    { path: "components/templates/auth-kit/auth-kit-theme.tsx" },
    { path: "components/templates/auth-kit/auth-kit-forms.tsx" },
    { path: "components/templates/auth-kit/auth-kit-pages.tsx" },
    { path: "app/auth/sign-in/page.tsx" },
    { path: "app/auth/sign-up/page.tsx" },
    { path: "app/auth/verify/page.tsx" },
    { path: "app/auth/forgot/page.tsx" },
    { path: "app/auth/reset/page.tsx" },
    { path: "app/auth/invite/page.tsx" },
    { path: "app/auth/onboarding/page.tsx" },
  ],
  dependencies: ["lucide-react"],
  registryDependencies: ["shadcn:utils", "aurora-background", "input-otp", "segmented-control"],
  examples: [
    { name: "template-auth-kit-demo", title: "Playground", file: "template-auth-kit-demo.tsx" },
    { name: "template-auth-kit-sign-in", title: "Sign in", file: "template-auth-kit-sign-in.tsx" },
    { name: "template-auth-kit-sign-up", title: "Sign up", file: "template-auth-kit-sign-up.tsx" },
    { name: "template-auth-kit-verify", title: "Verify", file: "template-auth-kit-verify.tsx" },
    { name: "template-auth-kit-forgot", title: "Forgot", file: "template-auth-kit-forgot.tsx" },
    { name: "template-auth-kit-reset", title: "Reset", file: "template-auth-kit-reset.tsx" },
    { name: "template-auth-kit-invite", title: "Invite", file: "template-auth-kit-invite.tsx" },
    { name: "template-auth-kit-onboarding", title: "Onboarding", file: "template-auth-kit-onboarding.tsx" },
  ],
  docs: "Routes are at /auth/sign-in, /auth/sign-up, /auth/verify, /auth/forgot, /auth/reset, /auth/invite and /auth/onboarding. Each form simulates its request with a short timer: replace the useFake() calls in auth-kit-forms.tsx with your API.",
  ai: {
    summary:
      "Installs a complete authentication flow. AuthKitPage renders one page in a layout (centered, split or glass); AuthKitPlayground lets you try every combination. Replace the simulated requests in auth-kit-forms.tsx with your auth provider.",
    whenToUse: ["Any product that needs sign in, sign up, verification and onboarding that look consistent", "Trying layouts quickly before you commit to one"],
    whenNotToUse: ["A single login box (use login-1 or login-2)"],
    composesWith: ["login-2", "verify-1", "onboarding-1"],
    a11y: [
      { keys: "Tab / Shift+Tab", action: "Moves through fields; the first invalid field is focused after a failed submit" },
      { keys: "Paste in the code field", action: "Fills all six digits at once" },
    ],
    customization: ["layout: centered, split or glass on each AuthKitPage", "Edit authCss for the light and dark palettes", "Replace the quote in the split layout"],
  },
  version: "1.0.0",
  updated: "2026-10-01",
})
