import { defineItem } from "@ballmac-ui/metadata"

export default defineItem({
  name: "template-atlas",
  type: "registry:block",
  title: "Atlas: store admin",
  description:
    "A dense, quiet six-page admin for an online store: a dashboard with a live date range, sortable orders with bulk actions, an order page with a refund flow, products, customers and settings.",
  category: "templates",
  templateKind: "application",
  templatePages: [
    { title: "Dashboard", example: "template-atlas-demo", path: "/atlas" },
    { title: "Orders", example: "template-atlas-orders", path: "/atlas/orders" },
    { title: "Order", example: "template-atlas-order", path: "/atlas/orders/ORD-10479" },
    { title: "Products", example: "template-atlas-products", path: "/atlas/products" },
    { title: "Customers", example: "template-atlas-customers", path: "/atlas/customers" },
    { title: "Settings", example: "template-atlas-settings", path: "/atlas/settings" },
  ],
  fonts: ["Manrope", "Geist Mono"],
  featured: true,
  tags: ["template", "admin", "dashboard", "ecommerce", "orders", "products", "customers", "settings"],
  files: [
    { path: "components/templates/atlas/atlas-fonts.ts" },
    { path: "components/templates/atlas/atlas-data.ts" },
    { path: "components/templates/atlas/atlas-theme.tsx" },
    { path: "components/templates/atlas/atlas-dashboard.tsx" },
    { path: "components/templates/atlas/atlas-orders.tsx" },
    { path: "components/templates/atlas/atlas-order.tsx" },
    { path: "components/templates/atlas/atlas-products.tsx" },
    { path: "components/templates/atlas/atlas-customers.tsx" },
    { path: "components/templates/atlas/atlas-settings.tsx" },
    { path: "app/atlas/page.tsx" },
    { path: "app/atlas/orders/page.tsx" },
    { path: "app/atlas/orders/[id]/page.tsx" },
    { path: "app/atlas/products/page.tsx" },
    { path: "app/atlas/customers/page.tsx" },
    { path: "app/atlas/settings/page.tsx" },
  ],
  dependencies: ["lucide-react", "recharts@^3"],
  registryDependencies: ["shadcn:utils", "badge", "checkbox", "chart", "command", "dialog", "dropdown-menu", "segmented-control", "sheet", "sparkline", "switch"],
  examples: [
    { name: "template-atlas-demo", title: "Dashboard", file: "template-atlas-demo.tsx" },
    { name: "template-atlas-orders", title: "Orders", file: "template-atlas-orders.tsx" },
    { name: "template-atlas-order", title: "Order", file: "template-atlas-order.tsx" },
    { name: "template-atlas-products", title: "Products", file: "template-atlas-products.tsx" },
    { name: "template-atlas-customers", title: "Customers", file: "template-atlas-customers.tsx" },
    { name: "template-atlas-settings", title: "Settings", file: "template-atlas-settings.tsx" },
  ],
  docs: "Pages are at /atlas, /atlas/orders, /atlas/orders/[id], /atlas/products, /atlas/customers and /atlas/settings. The palette is the atlasCss string in atlas-theme.tsx and the sample data is atlas-data.ts: replace it with calls to your own API.",
  ai: {
    summary:
      "Installs a six-page store admin with working client-side filtering, sorting, selection, drawers and forms over sample data. Replace atlas-data.ts with your API, and edit atlasCss for the palette.",
    whenToUse: ["Back offices for shops, marketplaces and internal tools", "A starting point for dense admin tables with bulk actions"],
    whenNotToUse: ["Public marketing sites (use a marketing template)"],
    composesWith: ["data-table", "dashboard-1", "settings-1"],
    a11y: [
      { keys: "⌘K / Ctrl+K", action: "Opens the search and navigation menu" },
      { keys: "Enter / Space on a column heading", action: "Sorts the table by that column" },
    ],
    customization: ["Replace atlas-data.ts with your data", "Edit atlasCss for the light and dark palettes", "Swap the sidebar items in the nav array of atlas-theme.tsx"],
  },
  version: "1.0.0",
  updated: "2026-10-01",
})
