/**
 * Axe on the open (and closed) states of overlay examples: menus, sheet, command dialog, combobox, navigation menu.
 * `pnpm a11y` scans each preview as rendered; this script also opens the overlays first, at desktop and 390 px
 * widths in light and dark, and screenshots each state to $SHOTS (default: the OS temp folder).
 *
 * Usage: start the production server (`next start -p 3301` in apps/www), then
 *   PLAYWRIGHT_CHROMIUM_EXECUTABLE=<chrome path, optional> tsx scripts/a11y-open-states.ts [name-filter…]
 *
 * Known upstream pattern, reported but not counted: Radix modal menus set aria-hidden on the page behind them
 * while focus is trapped in the menu, and NavigationMenu renders its own aria-hidden focus proxy. Axe flags both
 * as aria-hidden-focus.
 */
import AxeBuilder from "@axe-core/playwright"
import { chromium } from "playwright"
import { tmpdir } from "node:os"

const base = "http://127.0.0.1:3301"
type Step = (page: import("playwright").Page) => Promise<void>
const cases: Record<string, Step> = {
  "dropdown-menu-demo": async () => {},
  "dropdown-menu-states": async (p) => { await p.getByRole("button", { name: "Sort and view" }).click() },
  "context-menu-demo": async (p) => { await p.getByText("Q3 roadmap.pdf").click({ button: "right" }) },
  "context-menu-states": async (p) => { await p.getByText(/Grid (on|off)/).click({ button: "right" }) },
  "menubar-demo": async () => {},
  "menubar-states": async (p) => { await p.getByRole("menuitem", { name: "Appearance" }).click() },
  "sheet-demo": async (p) => { await p.getByRole("button", { name: "Edit project" }).click() },
  "sheet-states": async (p) => { await p.getByRole("button", { name: "Bottom" }).click() },
  "navigation-menu-demo": async () => {},
  "navigation-menu-states": async (p) => { await p.getByRole("button", { name: "Guides" }).click() },
  "command-dialog": async (p) => { await p.getByRole("button", { name: /Search commands/ }).click() },
  "combobox-demo": async (p) => { await p.getByRole("combobox").click() },
  "combobox-states": async (p) => { await p.getByRole("combobox").first().click() },
  "slider-demo": async (p) => { await p.getByRole("slider").first().focus() },
  "drawer-demo": async (p) => { await p.getByRole("button", { name: "Review order" }).click() },
  "drawer-states": async (p) => { await p.getByRole("button", { name: "Bottom" }).click() },
  "date-picker-demo": async (p) => { await p.getByRole("button", { name: /Delivery date/ }).click() },
  "date-picker-states": async (p) => { await p.getByRole("button", { name: /Date of birth|Select your birthday/ }).first().click() },
  "data-table-demo": async (p) => { await p.getByRole("button", { name: "Columns" }).click() },
  "form-demo": async (p) => { await p.getByRole("button", { name: "Create account" }).click() },
  "toast-demo": async (p) => { await p.getByRole("button", { name: "Error" }).click() },
  "toast-states": async (p) => { await p.getByRole("button", { name: "Action and cancel" }).click() },
  "sidebar-demo": async () => {},
  "sidebar-states": async () => {},
  "calendar-demo": async () => {},
  "calendar-states": async () => {},
  "carousel-demo": async () => {},
  "carousel-states": async () => {},
  "chart-demo": async () => {},
  "chart-bars": async () => {},
  "chart-donut": async () => {},
  "input-otp-demo": async (p) => { await p.getByRole("textbox").first().fill("111111") },
  "resizable-demo": async () => {},
  "navbar-demo": async (p) => { await p.getByRole("button", { name: "Menu" }).click({ timeout: 1500 }).catch(() => {}) },
  "navbar-states": async () => {},
  "mega-menu-demo": async (p) => { await p.getByRole("button", { name: "Product" }).click({ timeout: 1500 }).catch(() => {}) },
  "mega-menu-states": async (p) => { await p.getByText("Product").first().click() },
  "floating-nav-demo": async () => {},
  "floating-nav-states": async () => {},
  "app-shell-demo": async (p) => { await p.getByRole("button", { name: "Open navigation" }).click({ timeout: 1500 }).catch(() => {}) },
  "app-shell-states": async () => {},
  "team-switcher-demo": async (p) => { await p.getByRole("button", { name: /Acme Inc\./ }).click() },
  "team-switcher-states": async (p) => { await p.getByRole("button", { name: /Team: / }).click() },
  "sticky-scroll-demo": async () => {},
  "sticky-scroll-states": async () => {},
  "split-view-demo": async () => {},
  "split-view-states": async (p) => { await p.getByRole("button", { name: "Brand guidelines.pdf" }).click() },
  "masonry-grid-demo": async () => {},
  "masonry-grid-states": async () => {},
  "scroll-progress-demo": async () => {},
  "scroll-progress-states": async () => {},
  "back-to-top-demo": async (p) => { await p.getByLabel("Release notes").evaluate((el) => { el.scrollTop = 400 }) },
  "back-to-top-states": async (p) => { await p.getByLabel("Long page").evaluate((el) => { el.scrollTop = 200 }) },
  "table-of-contents-demo": async (p) => { await p.getByLabel("Guide").evaluate((el) => { el.scrollTop = 300 }) },
  "table-of-contents-states": async () => {},
  "container-scroll-demo": async () => {},
  "container-scroll-states": async () => {},
  "section-tabs-demo": async (p) => { await p.getByRole("link", { name: "Pricing" }).click() },
  "section-tabs-states": async (p) => { await p.getByRole("link", { name: "Reviews" }).click() },
  "onboarding-checklist-demo": async (p) => { await p.getByRole("button", { name: "Invite your team" }).click() },
  "onboarding-checklist-states": async () => {},
  "settings-panel-demo": async (p) => { await p.getByRole("checkbox", { name: /Weekly digest/ }).click({ timeout: 2000 }).catch(() => p.getByRole("switch", { name: /Weekly digest/ }).click()) },
  "settings-panel-states": async () => {},
  "usage-meter-demo": async () => {},
  "usage-meter-states": async () => {},
  "billing-card-demo": async () => {},
  "billing-card-states": async () => {},
  "plan-selector-demo": async (p) => { await p.getByRole("radio", { name: /Monthly/ }).check({ force: true }) },
  "plan-selector-states": async () => {},
  "invite-members-demo": async (p) => { await p.getByRole("textbox", { name: "Email addresses" }).fill("new@acme.example, bad@") ; await p.keyboard.press("Enter") },
  "invite-members-states": async () => {},
  "notification-center-demo": async () => {},
  "notification-center-states": async () => {},
  "feedback-widget-demo": async (p) => { await p.getByRole("radio", { name: "Happy", exact: true }).check({ force: true }) },
  "feedback-widget-states": async (p) => { await p.getByRole("button", { name: "Rate this page" }).click() },
  "changelog-feed-demo": async () => {},
  "changelog-feed-states": async () => {},
  "cookie-consent-demo": async (p) => { await p.getByRole("button", { name: "Customize" }).click() },
  "cookie-consent-states": async () => {},
  "user-menu-demo": async () => {},
  "user-menu-states": async (p) => { await p.getByRole("button", { name: /Account menu/ }).click() },
  "workspace-card-demo": async () => {},
  "workspace-card-states": async () => {},
  "command-bar-demo": async (p) => { await p.getByRole("button", { name: /Search or jump to/ }).click() },
  "command-bar-states": async (p) => { await p.getByRole("button", { name: /Open from your own button/ }).click() },
  "thinking-indicator-demo": async () => {},
  "thinking-indicator-variants": async () => {},
  "ai-orb-demo": async (p) => { await p.getByRole("button", { name: "Speaking" }).click() },
  "ai-orb-voice": async () => {},
  "suggestion-chips-demo": async (p) => { await p.getByRole("button", { name: "Explain this error" }).click() },
  "suggestion-chips-cards": async (p) => { await p.getByRole("button", { name: /Find the bug/ }).focus() },
  "citation-demo": async (p) => { await p.getByRole("link", { name: /Source 1/ }).focus() },
  "citation-pill": async (p) => { await p.getByRole("link", { name: /Source: Acme and 2 more/ }).focus() },
  "sources-list-demo": async (p) => { await p.getByRole("button", { name: "Hover or focus this" }).focus() },
  "sources-list-cards": async (p) => { await p.getByRole("button", { name: "Show all 5" }).click() },
  "chat-attachment-demo": async (p) => { await p.getByRole("button", { name: "Remove migration-notes.md" }).click() },
  "chat-attachment-tiles": async (p) => { await p.getByRole("button", { name: "Open whiteboard.png" }).click() },
  "model-picker-demo": async (p) => { await p.getByRole("combobox").click(); await p.keyboard.press("ArrowDown") },
  "model-picker-compact": async (p) => { await p.getByRole("combobox").click() },
  "token-meter-demo": async () => {},
  "token-meter-pill": async (p) => { await p.getByRole("button", { name: /Context window/ }).click() },
  "agent-plan-demo": async (p) => { await p.getByRole("button", { name: /Done: Read the repository/ }).click({ timeout: 15000 }) },
  "agent-plan-failed": async (p) => { await p.getByRole("button", { name: "Retry Send the summary to accounting" }).focus() },
  "approval-card-demo": async (p) => { await p.getByRole("button", { name: "Approve" }).click() },
  "approval-card-risks": async () => {},
  "voice-input-demo": async (p) => { await p.getByRole("button", { name: "Dictate a message" }).click() },
  "voice-input-button": async () => {},
  "artifact-panel-demo": async (p) => { await p.getByRole("tab", { name: "Code" }).click() },
  "artifact-panel-streaming": async () => {},
  "copy-button-demo": async (p) => { await p.getByRole("button", { name: "Copy", exact: true }).click() },
  "copy-button-inline": async () => {},
  "snippet-tabs-demo": async (p) => { await p.getByRole("tab", { name: "Python" }).click() },
  "snippet-tabs-variables": async () => {},
  "status-badge-row-demo": async (p) => { const s = p.getByRole("slider").first(); await s.focus(); await p.keyboard.press("ArrowLeft"); await p.keyboard.press("ArrowLeft") },
  "status-badge-row-incident": async (p) => { await p.getByRole("slider").first().focus() },
  "package-badge-demo": async () => {},
  "package-badge-inline": async () => {},
  "keyboard-shortcuts-demo": async () => {},
  "keyboard-shortcuts-dialog": async (p) => { await p.getByRole("button", { name: /Keyboard shortcuts/ }).click() },
  "api-endpoint-demo": async (p) => { await p.getByRole("tab", { name: "402" }).click() },
  "api-endpoint-list": async (p) => { await p.getByRole("button", { name: /^GET \/v1\/projects\/\{id\}/ }).click() },
  "env-editor-demo": async (p) => { await p.getByRole("button", { name: "Show all" }).click() },
  "env-editor-controlled": async () => {},
  "log-stream-demo": async () => {},
  "log-stream-static": async (p) => { await p.getByRole("button", { name: /ERROR/ }).first().click() },
  "webhook-card-demo": async (p) => { await p.getByRole("button", { name: /invoice\.paid/ }).first().click() },
  "webhook-card-failing": async (p) => { await p.getByRole("button", { name: /order\.created/ }).first().click() },
  "git-graph-demo": async (p) => { await p.getByRole("listbox").focus(); await p.keyboard.press("ArrowDown") },
  "git-graph-linear": async (p) => { await p.getByRole("option").nth(1).click() },
  "blur-fade-demo": async (p) => { await p.waitForTimeout(2200) },
  "blur-fade-directions": async (p) => { await p.waitForTimeout(2200) },
  "text-animate-demo": async (p) => { await p.waitForTimeout(3000) },
  "text-animate-characters": async (p) => { await p.waitForTimeout(3500) },
  "typing-text-demo": async (p) => { await p.waitForTimeout(4000) },
  "typing-text-once": async (p) => { await p.waitForTimeout(4500) },
  "hyper-text-demo": async (p) => { await p.waitForTimeout(3000) },
  "hyper-text-hover": async (p) => { await p.getByText("Hover me").first().focus(); await p.waitForTimeout(1500) },
  "sparkles-text-demo": async (p) => { await p.waitForTimeout(800) },
  "sparkles-text-gradient": async (p) => { await p.waitForTimeout(800) },
  "morphing-text-demo": async (p) => { await p.waitForTimeout(1500) },
  "morphing-text-inline": async (p) => { await p.waitForTimeout(1500) },
  "spinning-text-demo": async (p) => { await p.waitForTimeout(300) },
  "spinning-text-sizes": async (p) => { await p.waitForTimeout(300) },
  "highlighter-demo": async (p) => { await p.waitForTimeout(4000) },
  "highlighter-actions": async (p) => { await p.waitForTimeout(3500) },
  "rainbow-button-demo": async (p) => { await p.getByRole("button").first().focus() },
  "rainbow-button-sizes": async (p) => { await p.getByRole("button").first().focus() },
  "shiny-button-demo": async (p) => { await p.getByRole("button").first().hover(); await p.waitForTimeout(900) },
  "shiny-button-variants": async () => {},
  "pulse-button-demo": async () => {},
  "pulse-button-tones": async (p) => { await p.getByRole("button").first().click() },
  "ripple-demo": async () => {},
  "ripple-click": async (p) => { await p.getByText("Inbox").click() },
  "animated-list-demo": async (p) => { await p.waitForTimeout(5500) },
  "animated-list-log": async (p) => { await p.waitForTimeout(4500) },
  "stagger-list-demo": async (p) => { await p.getByRole("button", { name: "Overlays" }).click(); await p.waitForTimeout(1200) },
  "stagger-list-directions": async (p) => { await p.waitForTimeout(2000) },
  "in-view-demo": async (p) => { await p.waitForTimeout(2000) },
  "in-view-state": async () => {},
  "animated-number-flow-demo": async (p) => { await p.getByRole("button", { name: "Yearly" }).click(); await p.waitForTimeout(1500) },
  "animated-number-flow-formats": async (p) => { await p.getByRole("button", { name: "Raise" }).click(); await p.waitForTimeout(1800) },
  "circular-progress-demo": async (p) => { await p.waitForTimeout(2500) },
  "circular-progress-gauge": async (p) => { await p.waitForTimeout(2500) },
  "avatar-circles-demo": async (p) => { await p.getByRole("button", { name: /Ada Lovelace/ }).hover(); await p.waitForTimeout(500) },
  "avatar-circles-sizes": async (p) => { await p.getByRole("link", { name: "Ada" }).first().focus(); await p.waitForTimeout(400) },
  "magic-card-demo": async (p) => { const b = await p.getByText("Fast by default").boundingBox(); if (b) await p.mouse.move(b.x + 40, b.y + 10); await p.waitForTimeout(400) },
  "magic-card-colors": async (p) => { await p.getByText("Move over me").first().hover(); await p.waitForTimeout(400) },
  "neon-card-demo": async (p) => { await p.waitForTimeout(500) },
  "neon-card-tones": async (p) => { await p.waitForTimeout(500) },
  "glare-hover-demo": async (p) => { await p.getByRole("img").first().hover(); await p.waitForTimeout(500) },
  "glare-hover-tones": async (p) => { await p.getByText("Dark glare").hover(); await p.waitForTimeout(500) },
  "lens-demo": async (p) => { const b = await p.getByRole("img").first().boundingBox(); if (b) await p.mouse.move(b.x + b.width * 0.62, b.y + b.height * 0.45); await p.waitForTimeout(500) },
  "lens-text": async (p) => { await p.getByRole("group").first().focus(); await p.keyboard.press("ArrowRight"); await p.waitForTimeout(400) },
  "spring-drawer-demo": async (p) => { await p.getByRole("button", { name: "Open cart" }).click(); await p.waitForTimeout(1200) },
  "spring-drawer-side": async (p) => { await p.getByRole("button", { name: "From the right" }).click(); await p.waitForTimeout(1200) },
  "video-dialog-demo": async (p) => { await p.getByRole("button", { name: /Play video/ }).click(); await p.waitForTimeout(800) },
  "video-dialog-aspects": async () => {},
  "retro-grid-demo": async (p) => { await p.waitForTimeout(600) },
  "retro-grid-tones": async (p) => { await p.waitForTimeout(600) },
  "grid-pattern-demo": async (p) => { await p.waitForTimeout(400) },
  "grid-pattern-variants": async (p) => { await p.waitForTimeout(1800) },
  "interactive-grid-demo": async (p) => { const b = await p.getByText("Move your mouse").boundingBox(); if (b) { await p.mouse.move(b.x - 60, b.y); await p.mouse.move(b.x + 60, b.y + 20, { steps: 8 }) } },
  "interactive-grid-colors": async (p) => { const b = await p.getByText("Small cells").boundingBox(); if (b) { await p.mouse.move(b.x, b.y - 60); await p.mouse.move(b.x + 80, b.y - 20, { steps: 8 }) } },
  "warp-background-demo": async (p) => { await p.waitForTimeout(1000) },
  "warp-background-cards": async (p) => { await p.waitForTimeout(1000) },
  "light-rays-demo": async (p) => { await p.waitForTimeout(800) },
  "light-rays-tones": async (p) => { await p.waitForTimeout(800) },
  "noise-texture-demo": async () => {},
  "noise-texture-blends": async () => {},
  "progressive-blur-demo": async (p) => { await p.getByRole("region", { name: "Documents" }).hover(); await p.mouse.wheel(0, 140); await p.waitForTimeout(500) },
  "progressive-blur-sides": async () => {},
  "scroll-velocity-demo": async (p) => { await p.getByRole("region", { name: /Scroll here/ }).hover(); await p.mouse.wheel(0, 300); await p.waitForTimeout(700) },
  "scroll-velocity-logos": async (p) => { await p.getByRole("region", { name: /Scroll here/ }).hover(); await p.mouse.wheel(0, 200); await p.waitForTimeout(700) },
  "smooth-cursor-demo": async (p) => { const b = await p.getByText("Move around").boundingBox(); if (b) { await p.mouse.move(b.x, b.y + 40); await p.mouse.move(b.x + 90, b.y + 110, { steps: 10 }) } await p.waitForTimeout(500) },
  "smooth-cursor-custom": async (p) => { const b = await p.getByText("A floaty ring").boundingBox(); if (b) await p.mouse.move(b.x + 30, b.y - 30, { steps: 6 }); await p.waitForTimeout(500) },
  "icon-cloud-demo": async (p) => { await p.waitForTimeout(800) },
  "icon-cloud-links": async (p) => { await p.getByRole("link").first().focus(); await p.waitForTimeout(400) },
  "dotted-map-demo": async (p) => { await p.waitForTimeout(1800) },
  "dotted-map-regions": async (p) => { await p.waitForTimeout(800) },
  "table-states": async () => {},
  "field-demo": async () => {},
  "input-group-demo": async () => {},
  "mac-icons-demo": async () => {},
  "mac-icons-tones": async () => {},
  "mac-context-menu-demo": async (p) => { await p.getByText("Q3 Report.pdf").click({ button: "right" }); await p.waitForTimeout(300) },
  "mac-context-menu-view": async (p) => { await p.getByText(/Sorted by/).click({ button: "right" }); await p.waitForTimeout(300) },
  "toolbar-demo": async (p) => { await p.getByRole("button", { name: "Back" }).focus(); await p.keyboard.press("ArrowRight") },
  "toolbar-labeled": async () => {},
  "sheet-dialog-demo": async (p) => { await p.getByRole("button", { name: "Save Password…" }).click(); await p.waitForTimeout(700) },
  "sheet-dialog-form": async (p) => { await p.getByRole("button", { name: "Save As…" }).click(); await p.waitForTimeout(700) },
  "finder-window-demo": async (p) => { await p.getByRole("option").first().click(); await p.keyboard.press("ArrowRight") },
  "finder-window-list": async (p) => { await p.getByRole("option").nth(1).click() },
  "file-browser-demo": async (p) => { await p.getByRole("checkbox", { name: "Select readme.md" }).check() },
  "file-browser-grid": async (p) => { await p.getByRole("button", { name: /cover\.jpg/ }).click() },
  "desktop-icons-demo": async (p) => { await p.getByRole("option").first().click() },
  "desktop-icons-window": async () => {},
  "launchpad-demo": async (p) => { await p.getByRole("button", { name: "Open Launchpad" }).click(); await p.waitForTimeout(700) },
  "launchpad-many": async (p) => { await p.waitForTimeout(700); await p.keyboard.press("PageDown"); await p.waitForTimeout(500) },
  "window-manager-demo": async (p) => { await p.getByRole("button", { name: /minimi[sz]e/i }).first().click(); await p.waitForTimeout(500) },
  "window-manager-controlled": async (p) => { await p.getByRole("button", { name: "Open new window" }).click(); await p.waitForTimeout(400) },
  "tablet-frame-demo": async () => {},
  "tablet-frame-portrait": async () => {},
  "watch-frame-demo": async () => {},
  "watch-frame-workout": async () => {},
  "android-frame-demo": async () => {},
  "android-frame-buttons": async () => {},
  "lock-screen-demo": async (p) => { await p.getByLabel(/Password for/).fill("nope"); await p.keyboard.press("Enter"); await p.waitForTimeout(700) },
  "lock-screen-ios": async (p) => { await p.getByRole("button", { name: "Swipe up to unlock" }).focus() },
  "control-center-demo": async (p) => { await p.getByRole("button", { name: /AirDrop/ }).click(); await p.getByRole("slider").first().focus(); await p.keyboard.press("ArrowLeft") },
  "control-center-compact": async (p) => { await p.getByRole("button", { name: /Wi-Fi/ }).click() },
  "hud-demo": async (p) => { await p.getByRole("button", { name: "Volume up" }).click(); await p.waitForTimeout(600) },
  "hud-pill": async (p) => { await p.getByRole("slider").focus(); await p.keyboard.press("ArrowRight"); await p.waitForTimeout(600) },
  "widgets-demo": async () => {},
  "widgets-sizes": async () => {},
  // Blocks, batch A
  "header-2-demo": async (p) => { const m = p.getByRole("button", { name: "Open menu" }); if (await m.isVisible()) await m.click(); else await p.getByRole("button", { name: "Product" }).click(); await p.waitForTimeout(500) },
  "header-2-simple": async (p) => { const m = p.getByRole("button", { name: "Open menu" }); if (await m.isVisible()) await m.click(); else await p.getByRole("button", { name: "Learn" }).click(); await p.waitForTimeout(500) },
  "pricing-2-demo": async (p) => { await p.getByRole("radio", { name: "Monthly" }).click(); await p.waitForTimeout(600) },
  "pricing-2-custom": async () => {},
  "pricing-3-demo": async (p) => { await p.getByRole("button", { name: "Core" }).or(p.getByRole("radio", { name: "Starter" })).first().click() },
  "pricing-3-two": async () => {},
  "faq-2-demo": async (p) => { await p.getByRole("searchbox", { name: "Search questions" }).fill("single"); await p.getByRole("button", { name: /sign-on/ }).click(); await p.waitForTimeout(400) },
  "faq-2-compact": async (p) => { await p.getByRole("searchbox", { name: "Search questions" }).fill("zzzz") },
  "features-6-demo": async (p) => { await p.getByRole("tab", { name: "Security" }).click(); await p.waitForTimeout(500) },
  "features-6-two": async () => {},
  "features-5-demo": async (p) => { await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight / 2)); await p.waitForTimeout(800) },
  "features-5-custom": async () => {},
  "testimonials-2-demo": async (p) => { await p.getByRole("tab", { name: /Marcus Webb/ }).click(); await p.waitForTimeout(600) },
  "testimonials-2-autoplay": async () => {},
  "cta-3-demo": async (p) => { await p.getByRole("tab", { name: "npm", exact: true }).click() },
  "cta-3-custom": async () => {},
  "hero-6-demo": async () => {},
  "hero-6-custom": async () => {},
  "hero-7-demo": async (p) => { await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight)); await p.waitForTimeout(800) },
  "hero-7-custom": async () => {},
  "stats-1-demo": async () => {},
  "stats-1-simple": async () => {},
  "team-1-demo": async (p) => { await p.getByRole("link", { name: "Priya’s website" }).focus() },
  "team-1-small": async () => {},
  "footer-2-demo": async () => {},
  "footer-2-long": async () => {},
  // Blocks, batch B
  "blog-1-demo": async (p) => { await p.getByRole("button", { name: "Engineering" }).click() },
  "blog-1-compact": async () => {},
  "blog-post-1-demo": async (p) => { await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight / 2)); await p.waitForTimeout(600) },
  "blog-post-1-short": async () => {},
  "changelog-1-demo": async (p) => { await p.getByRole("button", { name: /older releases/ }).click(); await p.getByRole("button", { name: /^Fixed/ }).click() },
  "changelog-1-minimal": async () => {},
  "contact-1-demo": async (p) => { await p.getByRole("button", { name: /Send message/ }).click(); await p.waitForTimeout(300) },
  "contact-1-support": async (p) => {
    await p.getByRole("textbox", { name: /Name/ }).fill("Jordan Lee"); await p.getByRole("textbox", { name: /Email/ }).fill("jordan@acme.com")
    await p.getByRole("textbox", { name: /Message/ }).fill("The export button does nothing for me."); await p.getByRole("checkbox").click()
    await p.getByRole("combobox").click(); await p.getByRole("option", { name: "Bug report" }).click()
    await p.getByRole("button", { name: /Send message/ }).click(); await p.getByText("Message sent").waitFor()
  },
  "careers-1-demo": async (p) => { await p.getByRole("searchbox", { name: "Search roles" }).fill("zzz"); await p.waitForTimeout(300) },
  "careers-1-small": async () => {},
  "comparison-1-demo": async (p) => { const r = p.getByRole("radio", { name: "Legacy suite" }); if (await r.isVisible()) await r.click() },
  "comparison-1-single": async () => {},
  "newsletter-1-demo": async (p) => { await p.getByLabel("Email address").fill("nope"); await p.getByRole("button", { name: /Subscribe/ }).click() },
  "newsletter-1-simple": async (p) => { await p.getByLabel("Email address").fill("me@acme.com"); await p.getByRole("button", { name: /Sign me up/ }).click(); await p.getByText("You’re subscribed.").waitFor() },
  "error-1-demo": async (p) => { await p.getByRole("searchbox", { name: "Search the site" }).focus() },
  "error-1-server": async () => {},
  // Blocks, batch C
  "login-2-demo": async (p) => { await p.getByRole("button", { name: /^Sign in/ }).click(); await p.waitForTimeout(300) },
  "login-2-error": async (p) => { await p.getByRole("textbox", { name: "Email" }).fill("me@acme.com"); await p.getByLabel("Password", { exact: true }).fill("wrong"); await p.getByRole("button", { name: /^Sign in/ }).click(); await p.getByText(/don’t match/).waitFor() },
  "signup-1-demo": async (p) => { await p.getByLabel("Password", { exact: true }).fill("abc"); await p.getByRole("button", { name: /Create account/ }).click(); await p.waitForTimeout(300) },
  "signup-1-simple": async (p) => {
    await p.getByRole("textbox", { name: /Full name/ }).fill("Jordan Lee"); await p.getByRole("textbox", { name: /Work email/ }).fill("jordan@acme.com")
    await p.getByLabel("Password", { exact: true }).fill("Correct-Horse-9"); await p.getByRole("checkbox").click(); await p.getByRole("button", { name: /Start trial/ }).click(); await p.getByText("Check your inbox").waitFor()
  },
  "forgot-password-1-demo": async (p) => { await p.getByRole("textbox", { name: "Email" }).fill("me@acme.com"); await p.getByRole("button", { name: /Send reset link/ }).click(); await p.getByRole("heading", { name: "Check your email" }).waitFor() },
  "forgot-password-1-reset": async (p) => { await p.getByLabel("New password", { exact: true }).fill("Correct-Horse-9"); await p.getByLabel("Confirm password", { exact: true }).fill("nope"); await p.getByRole("button", { name: "Update password" }).click(); await p.waitForTimeout(300) },
  "verify-1-demo": async (p) => { await p.getByLabel("6-digit verification code").fill("000000"); await p.getByText(/That code isn’t right/).waitFor() },
  "verify-1-four": async (p) => { await p.getByLabel("4-digit verification code").fill("4242"); await p.getByRole("heading", { name: "You’re verified" }).waitFor() },
  "onboarding-1-demo": async (p) => { await p.getByRole("textbox", { name: /Workspace name/ }).fill("Northwind Studio"); await p.getByRole("button", { name: /Continue/ }).click(); await p.getByRole("heading", { name: /What will you use/ }).waitFor(); await p.getByRole("checkbox", { name: /Send invoices/ }).check({ force: true }) },
  "onboarding-1-custom": async (p) => {
    await p.getByRole("textbox", { name: /Workspace name/ }).fill("Fjord"); await p.getByRole("button", { name: /Continue/ }).click()
    await p.getByRole("checkbox", { name: /Ship faster/ }).check({ force: true }); await p.getByRole("button", { name: /Continue/ }).click()
    await p.getByRole("textbox", { name: "Email addresses" }).fill("maya@acme.com"); await p.keyboard.press("Enter"); await p.getByRole("button", { name: /Continue/ }).click()
    await p.getByRole("button", { name: "Create workspace" }).click(); await p.getByRole("heading", { name: /is ready/ }).waitFor()
  },
  "invite-1-demo": async (p) => { await p.getByRole("button", { name: "Accept invitation" }).click(); await p.getByRole("heading", { name: /Welcome to/ }).waitFor() },
  "invite-1-expired": async (p) => { await p.getByRole("button", { name: "Request a new invitation" }).click(); await p.getByRole("heading", { name: "Request sent" }).waitFor() },
  // Blocks, batch D
  "app-shell-1-demo": async (p) => { await p.getByRole("button", { name: /^Search/ }).first().click(); await p.getByRole("dialog").waitFor() },
  "app-shell-1-collapsed": async () => {},
  "dashboard-1-demo": async (p) => { await p.getByRole("radio", { name: "7 days" }).click(); await p.waitForTimeout(600) },
  "dashboard-1-week": async () => {},
  "dashboard-2-demo": async (p) => { await p.getByRole("switch", { name: "Compare" }).click(); await p.getByRole("radio", { name: "12 months" }).click(); await p.waitForTimeout(600) },
  "dashboard-2-week": async () => {},
  "settings-1-demo": async (p) => { await p.getByRole("textbox", { name: /Bio/ }).fill("Quiet dashboards, loud spreadsheets."); await p.getByRole("button", { name: "Save changes" }).waitFor() },
  "settings-1-save": async (p) => { await p.getByRole("textbox", { name: /Bio/ }).fill("Hello"); await p.getByRole("button", { name: "Save changes" }).click(); await p.getByText(/couldn’t save/).waitFor() },
  "settings-2-demo": async (p) => { await p.getByRole("radio", { name: /Weekly/ }).check({ force: true }); await p.getByRole("switch", { name: "Product news by Email" }).first().click(); await p.getByText("Saved").waitFor() },
  "settings-2-custom": async () => {},
  "settings-3-demo": async (p) => { await p.getByRole("textbox", { name: /Invite someone/ }).fill("nope"); await p.keyboard.press("Enter"); await p.waitForTimeout(300) },
  "settings-3-full": async (p) => { await p.getByRole("textbox", { name: /Invite someone/ }).fill("late@fjord.no"); await p.keyboard.press("Enter"); await p.waitForTimeout(300) },
  "billing-1-demo": async (p) => { await p.getByRole("button", { name: "Update card" }).click(); await p.getByRole("button", { name: "Save card" }).click(); await p.waitForTimeout(300) },
  "billing-1-starter": async () => {},
  "billing-2-demo": async (p) => { await p.getByRole("radio", { name: "Yearly · save 20%" }).click(); await p.waitForTimeout(300) },
  "billing-2-yearly": async () => {},
  "mail-1-demo": async (p) => { await p.getByRole("button", { name: /Stripe/ }).click(); const r = p.getByRole("button", { name: /Reply/ }); if (await r.isVisible()) await r.click(); await p.waitForTimeout(300) },
  "mail-1-empty": async () => {},
  "kanban-1-demo": async (p) => { await p.getByRole("button", { name: /^Redraw empty states/ }).focus(); await p.keyboard.press("Space"); await p.keyboard.press("ArrowRight"); await p.waitForTimeout(300) },
  "kanban-1-simple": async () => {},
  "calendar-1-demo": async (p) => { await p.getByRole("button", { name: /Lunch with Amara/ }).click(); await p.getByRole("dialog").waitFor() },
  "calendar-1-compact": async () => {},
  "ai-chat-2-demo": async (p) => { await p.getByRole("button", { name: "Add a monthly and yearly toggle" }).click(); await p.getByText(/added a monthly and yearly toggle/).waitFor({ timeout: 8000 }) },
  "ai-chat-2-blank": async () => {},
  "showcase-1-demo": async (p) => { await p.getByRole("menubar").getByText("Ledger", { exact: true }).click(); await p.getByRole("menu").waitFor() },
  "showcase-1-custom": async () => {},
  "download-1-demo": async (p) => { await p.getByRole("radio", { name: "Intel" }).click(); const l = p.getByRole("link", { name: /Download/ }); await l.evaluate((el) => el.addEventListener("click", (e) => e.preventDefault())); await l.click(); await p.getByText(/should start/).waitFor() },
  "download-1-simple": async () => {},
  "devices-1-demo": async (p) => { await p.getByRole("button", { name: /iPad/ }).click() },
  "devices-1-custom": async () => {},
  "features-7-demo": async (p) => { await p.getByRole("radio", { name: /Focus timer/ }).click(); await p.getByText(/session|Focus/).first().waitFor() },
  "features-7-two": async () => {},
  "pricing-4-demo": async (p) => { await p.getByRole("radio", { name: "Subscribe" }).click(); await p.getByRole("switch").click() },
  "pricing-4-custom": async () => {},
  "template-orbit-demo": async (p) => { const run = p.locator('[data-slot="orbit-agent-run"]'); await run.scrollIntoViewIfNeeded(); await run.locator('[role="status"]').filter({ hasText: "Completed" }).waitFor({ timeout: 15000 }) },
  "template-orbit-pricing": async (p) => { await p.getByRole("radio", { name: "Monthly" }).click(); await p.getByRole("slider").focus(); await p.keyboard.press("ArrowRight") },
  "template-orbit-changelog": async () => {},
  "template-orbit-login": async (p) => { await p.getByLabel("Work email").fill("ada@acme.co"); await p.getByRole("button", { name: /Email me a sign-in link/ }).click(); await p.getByText("Check your inbox").waitFor() },
  "template-relay-demo": async (p) => { await p.getByRole("button", { name: /^Send/ }).click(); await p.getByText("HTTP/1.1 202 Accepted").waitFor() },
  "template-relay-docs": async (p) => { await p.getByRole("tab", { name: "Python" }).first().click() },
  "template-relay-pricing": async (p) => { await p.getByRole("slider").focus(); await p.keyboard.press("ArrowRight") },
  "template-relay-status": async () => {},
  "template-ledger-demo": async () => {},
  "template-ledger-download": async (p) => { await p.getByRole("radio", { name: "Intel" }).click() },
  "template-ledger-pricing": async (p) => { await p.getByRole("radio", { name: "Subscribe" }).click() },
  "template-ledger-changelog": async () => {},
  "template-ledger-support": async (p) => { await p.getByRole("searchbox", { name: "Search help articles" }).fill("zzzz"); await p.getByText("Nothing found").waitFor() },
  "template-northwind-demo": async (p) => { await p.getByRole("radio", { name: /Budgets that warn early/ }).click() },
  "template-northwind-pricing": async (p) => { await p.getByRole("radio", { name: "Monthly" }).click(); await p.getByRole("button", { name: /Do I pay for every employee/ }).click() },
  "template-northwind-customers": async () => {},
  "template-northwind-about": async () => {},
  "template-northwind-contact": async (p) => { await p.getByRole("button", { name: "Request a demo" }).click(); await p.getByText("Tell us your name.").waitFor() },
  "template-atlas-demo": async (p) => { await p.getByRole("radio", { name: "7 days" }).click() },
  "template-atlas-orders": async (p) => { await p.getByRole("button", { name: /^Unpaid/ }).click(); await p.getByRole("checkbox", { name: "Select all orders on this page" }).click(); await p.getByRole("region", { name: "Bulk actions" }).waitFor() },
  "template-atlas-order": async (p) => { await p.getByRole("button", { name: /^Refund$/ }).click(); const d = p.getByRole("dialog"); await d.getByRole("button", { name: /^Refund/ }).click(); await d.getByRole("alert").waitFor() },
  "template-atlas-products": async (p) => { await p.getByRole("button", { name: /Add product/ }).first().click(); const d = p.getByRole("dialog"); await d.getByRole("button", { name: "Add product" }).click(); await d.getByText("Give the product a name.").waitFor() },
  "template-atlas-customers": async (p) => { await p.getByRole("button", { name: /Amara Okafor/ }).click(); await p.getByRole("dialog").waitFor() },
  "template-atlas-settings": async (p) => { await p.getByRole("switch", { name: "Weekly digest" }).click(); await p.getByRole("region", { name: "Save changes" }).waitFor() },
  "template-muse-demo": async (p) => { await p.getByRole("combobox", { name: /Muse 5/ }).click(); await p.getByRole("option", { name: /Muse 5 Fast/ }).waitFor() },
  "template-muse-new": async (p) => { await p.getByRole("textbox", { name: "Message Muse" }).fill("Plan my week"); await p.keyboard.press("Enter"); await p.getByText(/Here is a calm way/).waitFor({ timeout: 8000 }) },
  "template-muse-projects": async (p) => { await p.getByRole("button", { name: /Add file/ }).click() },
  "template-muse-library": async (p) => { await p.getByRole("button", { name: /Debounce hook/ }).click(); await p.getByRole("dialog").waitFor() },
  "template-muse-settings": async (p) => { await p.getByLabel(/Type delete my account/).fill("delete my account") },
  "template-workspace-demo": async (p) => { await p.getByRole("button", { name: "Start" }).click(); await p.getByRole("checkbox", { name: /Review Dev/ }).check() },
  "template-workspace-mail": async () => {},
  "template-workspace-calendar": async () => {},
  "template-workspace-board": async () => {},
  "template-workspace-settings": async () => {},
  "template-auth-kit-demo": async (p) => { await p.getByRole("button", { name: "Sign up" }).click(); await p.getByLabel("Password", { exact: true }).fill("abc"); await p.getByText("Strength: Weak").waitFor() },
  "template-auth-kit-sign-in": async (p) => { await p.getByRole("button", { name: "Sign in" }).click(); await p.getByText(/Enter an email like/).waitFor() },
  "template-auth-kit-sign-up": async (p) => { await p.getByRole("button", { name: "Create account" }).click(); await p.getByText("Tell us your name.").waitFor() },
  "template-auth-kit-verify": async (p) => { await p.getByRole("textbox").fill("111111"); await p.getByText(/isn’t right/).waitFor() },
  "template-auth-kit-forgot": async (p) => { await p.getByRole("button", { name: "Send reset link" }).click(); await p.getByText(/Enter an email like/).waitFor() },
  "template-auth-kit-reset": async (p) => { await p.getByRole("button", { name: "Update password" }).click(); await p.getByText(/Meet every rule/).waitFor() },
  "template-auth-kit-invite": async () => {},
  "template-auth-kit-onboarding": async (p) => { await p.getByRole("button", { name: /Continue/ }).click(); await p.getByRole("heading", { name: "Name your workspace" }).waitFor() },
}
const filter = process.argv.slice(2)
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE })
let bad = 0
for (const [name, step] of Object.entries(cases)) {
  if (filter.length && !filter.some((f) => name.includes(f))) continue
  for (const theme of ["light", "dark"]) {
    for (const [w, h, tag] of [[1100, 800, "d"], [390, 800, "m"]] as const) {
      const ctx = await browser.newContext({ viewport: { width: w, height: h }, colorScheme: theme as "light" | "dark" })
      const page = await ctx.newPage()
      const errors: string[] = []
      page.on("pageerror", (e) => errors.push(e.message))
      page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()) })
      await page.addInitScript((t) => { try { localStorage.setItem("bm-theme", t) } catch {} }, theme)
      await page.goto(`${base}/preview/${name}?theme=${theme}`, { waitUntil: "networkidle" })
      await page.evaluate((t) => { document.documentElement.classList.toggle("dark", t === "dark"); document.documentElement.dataset.theme = t }, theme)
      await step(page)
      await page.waitForTimeout(500)
      const res = await new AxeBuilder({ page }).analyze()
      // Radix modal menus set aria-hidden on the page behind them while focus is trapped in the menu, and
      // navigation-menu renders its own aria-hidden focus proxies; axe flags both as aria-hidden-focus. Reported separately.
      const all = res.violations.filter((x) => x.impact === "serious" || x.impact === "critical")
      const known = all.filter((x) => x.id === "aria-hidden-focus")
      if (known.length) console.log(`${name} ${theme} ${tag}: (known Radix aria-hidden-focus, ${known[0].nodes.length} node)`)
      const v = all.filter((x) => x.id !== "aria-hidden-focus")
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
      for (const x of v) { bad++; console.log(`${name} ${theme} ${tag}: ${x.impact} ${x.id}\n   ${x.nodes.slice(0,2).map((n) => n.html.slice(0, 160)).join("\n   ")}`) }
      if (overflow) { bad++; console.log(`${name} ${theme} ${tag}: horizontal overflow`) }
      if (errors.length) { bad++; console.log(`${name} ${theme} ${tag}: console errors ${errors.slice(0,2)}`) }
      await page.screenshot({ path: `${process.env.SHOTS ?? tmpdir()}/${name}-${theme}-${tag}.png` })
      await ctx.close()
    }
  }
}
await browser.close()
console.log(bad ? `${bad} problem(s)` : "open states: all clean")
