import { DEFAULT_SPEC, normalizeSpec, type ThemeSpec } from "./engine"

export type ThemePreset = {
  slug: string
  title: string
  /** One short line for cards. */
  tagline: string
  /** One or two sentences for the registry and docs. */
  description: string
  /** What it suits, for the registry's `ai.whenToUse`. */
  suits: string[]
  spec: ThemeSpec
}

const preset = (slug: string, title: string, tagline: string, description: string, suits: string[], spec: Partial<ThemeSpec>): ThemePreset => ({
  slug,
  title,
  tagline,
  description,
  suits,
  spec: normalizeSpec({ ...DEFAULT_SPEC, ...spec }),
})

/** Twelve ready-made themes. Each is generated by the same engine as the builder, so contrast is checked for all of them in the tests. */
export const PRESETS: ThemePreset[] = [
  preset("graphite", "Graphite", "Quiet greys, ink buttons", "Neutral greys with near-black buttons and a calm blue focus ring. The safest starting point for any product.", ["Dashboards and admin tools", "Products that should look neutral and let content lead"], {
    hue: 255, chroma: 0.12, neutralHue: 255, neutralChroma: 0.004, radius: 0.5,
  }),
  preset("ocean", "Ocean", "Clear blue, friendly corners", "A confident blue brand colour on cool, lightly tinted greys with soft corners.", ["SaaS and fintech products", "Anything that should feel trustworthy"], {
    hue: 248, chroma: 0.17, neutralHue: 248, neutralChroma: 0.008, radius: 0.625, primary: "brand",
  }),
  preset("indigo", "Indigo", "Deep blue-violet, rounder", "Indigo buttons and accents with generous corners. Feels modern without being loud.", ["Developer tools and AI products", "Marketing sites that want a distinct colour"], {
    hue: 277, chroma: 0.2, neutralHue: 277, neutralChroma: 0.008, radius: 0.75, primary: "brand",
  }),
  preset("violet", "Violet", "Rich purple, very round", "A saturated purple with pill-like corners and slightly warm greys for a playful, creative feel.", ["Creative tools and communities", "Consumer apps"], {
    hue: 305, chroma: 0.22, neutralHue: 305, neutralChroma: 0.01, radius: 1, primary: "brand",
  }),
  preset("rose", "Rose", "Warm pink-red, soft", "A warm rose brand colour with blush-tinted greys and soft corners.", ["Lifestyle, health and community products", "Shops with a friendly voice"], {
    hue: 12, chroma: 0.19, neutralHue: 12, neutralChroma: 0.008, radius: 0.75, primary: "brand",
  }),
  preset("ember", "Ember", "Burnt orange, crisp", "Orange buttons on warm greys with tighter corners. Energetic but readable.", ["Developer platforms and media", "Calls to action that must stand out"], {
    hue: 45, chroma: 0.17, neutralHue: 60, neutralChroma: 0.008, radius: 0.5, primary: "brand",
  }),
  preset("amber", "Amber", "Ink buttons, golden accents", "Near-black buttons with amber focus rings and charts on warm paper-tinted greys.", ["Editorial and docs sites", "Brands that want warmth without a coloured button"], {
    hue: 80, chroma: 0.16, neutralHue: 80, neutralChroma: 0.008, radius: 0.375, paper: true,
  }),
  preset("forest", "Forest", "Deep green, grounded", "A deep green brand colour with slightly green greys and medium corners.", ["Sustainability, finance and wellness", "Products that should feel calm and established"], {
    hue: 152, chroma: 0.14, neutralHue: 152, neutralChroma: 0.008, radius: 0.5, primary: "brand",
  }),
  preset("teal", "Teal", "Fresh blue-green, round", "A fresh teal with cool greys and rounded corners.", ["Health, data and productivity apps", "Dashboards that want a friendly tone"], {
    hue: 192, chroma: 0.12, neutralHue: 200, neutralChroma: 0.008, radius: 0.875, primary: "brand",
  }),
  preset("sand", "Sand", "Warm paper, terracotta", "Off-white paper tones with terracotta accents and small, precise corners. Reads like print.", ["Portfolios, publications and studios", "Shops with a crafted feel"], {
    hue: 40, chroma: 0.13, neutralHue: 80, neutralChroma: 0.012, radius: 0.375, paper: true, primary: "brand",
  }),
  preset("mono", "Mono", "Pure black and white, square", "No colour at all: black, white and greys, square corners and borders strong enough to meet 3:1 contrast.", ["Brutalist and technical products", "Teams that need maximum contrast"], {
    hue: 0, chroma: 0, neutralHue: 0, neutralChroma: 0, radius: 0, edge: "strong",
  }),
  preset("midnight", "Midnight", "Electric sky blue, strong edges", "A bright sky-blue brand colour with strong outlines. Built to look best in dark mode.", ["Developer and gaming products", "Apps used mostly in dark mode"], {
    hue: 225, chroma: 0.16, neutralHue: 250, neutralChroma: 0.012, radius: 0.625, primary: "brand", edge: "strong",
  }),
]

export const getPreset = (slug: string) => PRESETS.find((p) => p.slug === slug)
